{% set name = "slick_queue_py" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Option 1: Local build (for testing before publishing)
  path: ..

  # Option 2: From PyPI (after publishing to PyPI - uncomment and add sha256)
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # sha256: <will be generated after first PyPI upload>

  # Option 3: From Git (use this after GitHub publication)
  # git_url: https://github.com/SlickQuant/slick_queue_py.git
  # git_rev: v{{ version }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  # Skip Python 2.x and 3.7 and below
  skip: true  # [py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=45
    - wheel
  run:
    - python >=3.8

test:
  imports:
    - slick_queue_py
    - atomic_ops
  commands:
    - python -c "import slick_queue_py; print('Version:', slick_queue_py.__version__)"
    - python -c "from slick_queue_py import SlickQueue, AtomicCursor"
    - python -c "from atomic_ops import check_platform_support; print(check_platform_support())"

about:
  home: https://github.com/SlickQuant/slick_queue_py
  license: MIT
  license_file: LICENSE
  summary: Lock-free MPMC queue with C++ interoperability via shared memory
  description: |
    Python implementation of SlickQueue - a lock-free multi-producer
    multi-consumer (MPMC) queue with C++ interoperability through shared memory.

    Features:
    - Dual Mode Operation (Local Memory / Shared Memory)
    - Lock-Free Multi-Producer Multi-Consumer
    - C++/Python Interoperability
    - Cross-Platform (Windows, Linux, macOS)
    - High Performance with hardware atomic operations
  doc_url: https://github.com/SlickQuant/slick_queue_py#readme
  dev_url: https://github.com/SlickQuant/slick_queue_py

extra:
  recipe-maintainers:
    - SlickQuant
    - kzhdev
